name: tour_tracker
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dcli: ^1.12.4
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
